"""remove asset name unique constraint

Revision ID: 0bde54e92a7d
Revises: 1a973c1e55c6
Create Date: 2026-09-14 22:39:48.808440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bde54e92a7d'
down_revision: Union[str, None] = '1a973c1e55c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_asset_project_name', 'assets', type_='unique')
    op.create_index('ix_asset_source_type', 'assets', ['asset_source_type'], unique=False)
    op.drop_constraint('uq_chunk_asset_order', 'chunks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_chunk_asset_order', 'chunks', ['chunk_asset_id', 'chunk_order'])
    op.drop_index('ix_asset_source_type', table_name='assets')
    op.create_unique_constraint('uq_asset_project_name', 'assets', ['asset_project_id', 'asset_name'])
    # ### end Alembic commands ###
