"""added columns to chunk table

Revision ID: 338231fb33e9
Revises: 0bde54e92a7d
Create Date: 2026-09-15 19:59:55.300950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '338231fb33e9'
down_revision: Union[str, None] = '0bde54e92a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('chunk_strategy', sa.String(), nullable=True))
    op.add_column('chunks', sa.Column('chunk_char_count', sa.Integer(), nullable=True))
    op.add_column('chunks', sa.Column('chunk_token_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'chunk_token_count')
    op.drop_column('chunks', 'chunk_char_count')
    op.drop_column('chunks', 'chunk_strategy')
    # ### end Alembic commands ###
